openapi: 3.1.0
info:
  title: DeBank API
  description: API for accessing DeBank's cryptocurrency wallet information, including net curves.
  version: '1.0.0'
servers:
  - url: https://pro-openapi.debank.com
    description: DeBank OpenAPI Server
paths:
  /v1/user/total_net_curve:
    get:
      operationId: getUserTotalNetCurve
      summary: Get 24-hour net curve of user on all chains.
      parameters:
        - name: id
          in: query
          required: true
          description: The user's wallet address.
          schema:
            type: string
        - name: chain_ids
          in: query
          required: false
          description: Optional. A comma-separated list of chain IDs (e.g., eth, bsc, xdai). All chains by default.
          schema:
            type: string
      responses:
        '200':
          description: Returns timestamp and value of user's assets at each timestamp.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    timestamp:
                      type: number
                      format: double
                      description: The timestamp on the curve.
                    usd_value:
                      type: number
                      format: double
                      description: The total value of the user's assets at the given timestamp.
components:
  securitySchemes:
    apiKey:
      type: apiKey
      in: header
      name: AccessKey
security:
  - apiKey: []
